### ISSUE TITLE
Send mail error in a test environment dnn 9

### ISSUE THREAD

**Issue by mangiove** [2sic/app-mobius-forms#1]
Hello, just trying out this awesome app, in dnn 8 it seems working well. 
In a test environment using dnn 9 it gives error sending email.
Don't know if it is dnn 9 version the cause, but it seems it is looking for an api in the wrong place

The form example is here http://www.msgweb.it/chisiamo
> 
jquery.js?cdv=103:8526 POST http://www.msgweb.it/API/2sxc/app-api/Form/ProcessForm? 404 (Not Found)

Thanks you
Kinds regards

**Comment by iJungleboy** [comment]
Fiddler says: 
`{"Message":"Impossibile individuare un controller per http://www.msgweb.it/API/2sxc/app-api/Form/ProcessForm. Ricerca nei namespace: ToSic.SexyContent.Apps."}`

I don't have an explanation yet, but I'll look into it in a few days.

**Comment by iJungleboy** [comment]
And thanks for the live demo, much faster to see what's going on :)

**Comment by iJungleboy** [comment]
Found the reason, it's the changed url of API calls in dnn9 - will fix soon:

https://github.com/2sic/2sxc/issues/1099

**Comment by mangiove** [comment]
Nice one! Thanks you :)

**Comment by iJungleboy** [comment]
Note: fixed it - will be in 2sxc 8.9.1
