### ISSUE TITLE
Error after installing the App and adding to page

### ISSUE THREAD

**Issue by andyduo** [2sic/app-mobius-forms#14]
Just installed Mobius Form 2 App on 2sxc 9.3 and DNN 8.0.3 but when I add the form to the page I get the following error:
`
Error: System.IO.FileLoadException: Could not load file or assembly 'System.Web.Helpers, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) File name: 'System.Web.Helpers, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' at Connect.Dnn.Koi.DnnSkinFile.AutoDetect() at Connect.Koi.Context.HttpContextState.TryToDetectTheCssFramework() at Connect.Koi.Context.HttpContextState.get_CssFramework() at Connect.Koi.Context.ToolsForCurrentState.get_Css() at Connect.Koi.Koi.Class(String classes) at ASP._Page_Portals_9_2sxc_Mobius_Forms__Contact_Form_cshtml.Execute() in c:\inetpub\vhosts\zzzzzzzzzzzzzzzzzzzz.co.nz\httpdocs\Portals\9\2sxc\Mobius Forms\_Contact Form.cshtml:line 32 at System.Web.WebPages.WebPageBase.ExecutePageHierarchy() at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage) at ToSic.SexyContent.Engines.RazorEngine.Render(TextWriter writer) in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\2Sexy Content Razor\RazorEngine.cs:line 65 at ToSic.SexyContent.Engines.RazorEngine.RenderTemplate() in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\2Sexy Content Razor\RazorEngine.cs:line 92 at ToSic.SexyContent.Engines.EngineBase.Render() in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\ToSic.Sxc\SexyContent\Engines\EngineBase.cs:line 92 at ToSic.SexyContent.SxcInstance.Render() in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\ToSic.Sxc\SexyContent\SxcInstance_Render.cs:line 58 WRN: Assembly binding logging is turned OFF. To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1. Note: There is some performance penalty associated with assembly bind failure logging. To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].`

Any ideas how this might be fixed? Thank you.

**Comment by iJungleboy** [comment]
did you add it to 2sxc 9.3 or 9.30? it needs 9.30 because Mobius 2 uses Koi for CSS framework detection.

**Comment by andyduo** [comment]
@iJungleboy Sorry just getting back to this now. I'm using DNN 9.2 and 2sxc 9.32.00 LTS on a site but still get the above error after adding Forms app to the page.

**Comment by iJungleboy** [comment]
Two things: the first version-issue is probably related to https://github.com/2sic/2sxc/issues/1595 - check that out. 
The second thing looks like your koi.json is faulty (not valid json?)
