### ISSUE TITLE
Using a form field value for the to address

### ISSUE THREAD

**Issue by andyduo** [2sic/app-mobius-forms#18]
I have a form based on simple contact form. I have added a dropdown field called SendTo. Is it possible to use that value to set the Owner Email address so the form can be submitted to different departments?

**Comment by iJungleboy** [comment]
This is simple. Best place to do this is to copy the WebAPI endpoint and make the changes in the C# code. We always recommend copying, to ensure that you still have the original endpoint for other forms.
