### ISSUE TITLE
Can't use 2SXC

### ISSUE THREAD

**Issue by juantarte** [2sic/app-mobius-forms#21]
After several tries finally error list goes really short, this is the last error i got and can not find information about it.   I don't have the files on C:\Projects\2sxc-dnn742\Website\DesktopModules we have it on C:\webapps\DNN7\DesktopModules

Error: Content is currently unavailable. DotNetNuke.Services.Exceptions.ModuleLoadException: Error - can't find 2sxc instance configuration. Probably trying to show an app or content that has been deleted. ---> System.Exception: Error - can't find 2sxc instance configuration. Probably trying to show an app or content that has been deleted. at ToSic.SexyContent.View.Page_PreRender(Object sender, EventArgs e) in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\View.ascx.cs:line 63 --- End of inner exception stack trace ---

**Comment by iJungleboy** [comment]
@juantarte I don't understand what you're describing. Could you please give more context, like "I installed it the first time" or "it suddenly stopped working after an update" or anything like that? and just some more infos otherwise we can't really help you.

**Comment by iJungleboy** [comment]
I'm not even sure if this is a Mobius or a 2sxc issue - can you verify?

**Comment by juantarte** [comment]
Sorry was my mistake to did it on Mobius, was 2sxc issue.

I finally install 2sxc.

**Comment by iJungleboy** [comment]
So please post on 2sxc, not on mobius - different people who would respond. 
Note that this looks more like a support thing - in which case StackOverflow would be the right place to put it.

**Comment by dzsquared** [comment]
> Sorry was my mistake to did it on Mobius, was 2sxc issue.
> 
> I finally install 2sxc.

@juantarte I understand this was a 2sxc issue for you - I am also stuck trying to install 2sxc on DNN 8 and receiving that error when adding content or app modules to a page.  how did you complete the install?

**Comment by juantarte** [comment]
> > Sorry was my mistake to did it on Mobius, was 2sxc issue.
> > I finally install 2sxc.
> 
> @juantarte I understand this was a 2sxc issue for you - I am also stuck trying to install 2sxc on DNN 8 and receiving that error when adding content or app modules to a page. how did you complete the install?

Hi, really i don't remember what i do to install it, i\I do several's things trying an failing.   Just follow all steps they have on web, click all links and read all possibles solutions.

**Comment by iJungleboy** [comment]
I'm a bit confused as to what issue we're discussing here. Please post new issues in the right boards.
