### ISSUE TITLE
Installing (Import) the App Fails, 2sxcApp_Forms_03.10.01.zip

### ISSUE THREAD

**Issue by Accuraty** [2sic/app-mobius-forms#22]
After upgrading a site to DNN v9.04.04 and 2sxc to v10.24, I tried to Import 2sxcApp_Forms_03.10.01.zip the normal way and got the following error:

![image](https://user-images.githubusercontent.com/653301/71314635-7f7a8000-2411-11ea-9cd0-eabd026c70ca.png)

**Comment by iJungleboy** [comment]
I was able to install it without an issues. maybe restart DNN?
Will close this issue for now, if it doesn't resolve itself and/or you find out more, I'll reopen.

**Comment by Accuraty** [comment]
Tried again, got another error ('while updating entries'). So I manually cleaned out the installed stuff, then deleted the stray App (name was a GUID). Poked around, restarted apppool, tried again and it worked. Worked!! Cheers! And thank you.
