### ISSUE TITLE
Send doesn't hide recaptcha

### ISSUE THREAD

**Issue by micahsdad1402** [2sic/app-mobius-forms#30]
Send should be hiding recaptcha on submission.

If the page is left open, then the recaptcha expires.

See attached screen shot.
![2020-06-01_18-16-33](https://user-images.githubusercontent.com/15971421/83381257-4ddff900-a434-11ea-9121-dc11860c5e29.png)

**Comment by iJungleboy** [comment]
Just so you know, it's not a priority for the core team, but we would appreciate a contribution from the community for this. 

Just a note, the behavior would need to be more complex:

1. Hide on submit
1. Re-show if failed submit
1. Keep hidden if submit successful
1. If multiple forms are shown on the page, this show/hide should only affect the current form

**Comment by iJungleboy** [comment]
Since Mobius 5 uses the new, hidden recaptcha, this issue isn't relevant any more.
