### ISSUE TITLE
Bug in Razor code in the Generic Smart Form Example (fix included)

### ISSUE THREAD

**Issue by skarpik** [2sic/app-mobius-forms#48]
**Mobius V5.03.01 Hybrid
DNN v.9.10.02
2SXC v12.10.0**

Running the Generic Smart Form example without modification results in the following error:

Message:Customer Send mail failed: d:\Websites\dnn-9-10-2\Website\Portals\0\2sxc\MobiusForms5\live\email-templates\EmailToCustomerWithData.cs(24): error CS1061: 'System.Collections.Generic.Dictionary<string,object>' does not contain a definition for 'Subject' and no extension method 'Subject' accepting a first argument of type 'System.Collections.Generic.Dictionary<string,object>' could be found (are you missing a using directive or an assembly reference?)

Replacing line 24:

<strong>" + data.Subject + @"</strong>

with

<strong>" + data["Subject"] + @"</strong>

appears to fix the problem (no errors and the output looks correct).

**Comment by iJungleboy** [comment]
@maaaximum

**Comment by skarpik** [comment]
Thank you very much for fixing this.

**Comment by skarpik** [comment]
Thank you very much for fixing this.
