### ISSUE TITLE
Wish: Example with attachment

### ISSUE THREAD

**Issue by iJungleboy** [2sic/app-mobius-forms#5]
If we want to implement this, we would have to

1. Create a content-type with an adam field
2. Specify how the JS should send attachments, and how to tell the API for which "field" it's meant
2. Modify the API to also save attachments

**Comment by roman-yagodin** [comment]
Any progress on that? It would be really nice to have Mobius Forms example with attachments, as the requirement is pretty common while custom implementation looks challenging.

Maybe you could share some real-world examples?

**Comment by iJungleboy** [comment]
@roman-yagodin we would love to do that, but we're a bit short on resources ATM. Priorities are next release of 2sxc (much faster, most code converted to typescript, ....) etc.

**Comment by iJungleboy** [comment]
fyi: we've implemented it :)

It will be in the next release, but require 2sxc 9.30.
