### ISSUE TITLE
Fields missing even if everything is filled

### ISSUE THREAD

**Issue by eXistenZe** [2sic/app-mobius-forms#55]
Even when all fields are filled, mobius says something is missing.

I hope all this testing and bug reporting earns me some patronage points :)

![image](https://user-images.githubusercontent.com/26518879/172935341-f296ac36-06ed-4bb4-b1f1-89e24acd3a48.png)

**Comment by iJungleboy** [comment]
@maaaximum-at-2sic can you reproduce this?

**Comment by iJungleboy** [comment]
@eXistenZe is this a standard form, or one you made?

**Comment by maaaximum-at-2sic** [comment]
Couldn't reproduce.
--
Tested using:
| Name | Version |
| - | - |
| DNN | 9.10.2|
| 2sxc | 14.01|
| Mobius Forms | 5.04 |

Can you tell me more about your setup @eXistenZe ?

**Comment by eXistenZe** [comment]
Same settings.
Activated recaptcha and set the keys.
The challenge does show. Then I get the missing field red info.

One warning on browser log:
DevTools failed to load source map: Could not load content for https://woundcare.app/desktopmodules/tosic_sexycontent/dist/turnOn/turn-on.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by maaaximum-at-2sic** [comment]
@eXistenZe what version of reCAPTCHA do you use? Our implementation uses reCAPTCHA v3.

**Comment by eXistenZe** [comment]
The guide says v2

**Comment by maaaximum-at-2sic** [comment]
I have updated the guide with the correct reCAPTCHA version (v3). Thank you @eXistenZe :smile:.
Can you check if the bug is still present using reCAPTCHA v3?

**Comment by eXistenZe** [comment]
Now it goes to the api but there is still an error:
"Message":"Bad Request",
   "ExceptionMessage":"The remote server returned an error: (400) Bad Request.",
   "ExceptionType":"System.Net.WebException",
   "StackTrace":"   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)\r\n   at System.Net.WebClient.DownloadString(Uri address)\r\n   at Recaptcha.Validate(String encodedResponse) in c:\\inetpub\\vhosts\\x.x\\x.x\\Portals\\0\\2sxc\\MobiusForms5\\staging\\api\\Parts\\Recaptcha.cs:line 25\r\n   at CallSite.Target(Closure , CallSite , Object , String )\r\n   at FormController.ProcessForm(Dictionary`2 contactFormRequest, String workflowId) in c:\\inetpub\\vhosts\\x.x\\x.x\\Portals\\0\\2sxc\\MobiusForms5\\staging\\api\\FormController.cs:line 27\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_1.<GetExecutor>b__0(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__17`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__17`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext()"
}

**Comment by maaaximum-at-2sic** [comment]
This error couldn't be reproduced and may be caused due to file modification or outside influence, such as a firewall.
Please try installing Mobius-Forms on a new DNN installation with the newest 2sxc and new reCAPTCHA setup.

This project is open source, so feel free to create a pull request with your solution anytime. 😏

**Comment by eXistenZe** [comment]
I apologize for the delay.
I reinstalled everything and started all over, one step at a time.
I got the errors all over the place again, even the missing recaptcha key fixed in the last update.
One thing I've learned: this app is heavily dependent on clearing dnn cache after changing settings, specially recaptcha related.
It seems to be working fine now. Thanks.

**Comment by iJungleboy** [comment]
@eXistenZe thanks for the update that it works now, and also the hint or dnn-cache. We were not aware of that.
