### ISSUE TITLE
Json error with 05.04.00 and 2sxc 14.10.0

### ISSUE THREAD

**Issue by eXistenZe** [2sic/app-mobius-forms#57]
After one of the latest updates, all my mobius apps show this error after clicking send e-mail.

Unable to cast object of type 'System.Text.Json.Nodes.JsonArray' to type 'Newtonsoft.Json.Linq.JArray'.
StackTrace:
at FormController.ProcessForm(Dictionary`2 contactFormRequest, String workflowId) in ...\Portals\0\2sxc\MobiusForms5\staging\api\FormController.cs:line 73

**Comment by iJungleboy** [comment]
I believe this was an introduced by accident when we migrated from Newtonsoft to System.Text.Json. Please use the latest v14 LTS, I believe it's already fixed quite a while ago.
