### ISSUE TITLE
Translate label

### ISSUE THREAD

**Issue by FabioParigi** [2sic/app-mobius-forms#9]
Hi Dears
excuse me I'm new in 2sc, I try with interest the form app.
Can you explain me how to translate the labels? I have 2 language website dnn v9.1

I try to follow the https://github.com/2sic/app-mobius-forms/wiki/Translate
but where is the **App Resources**, switch to the language tab, and translate

thanks
Fabio

**Comment by iJungleboy** [comment]
The resources are at app-level. Go to the app settings, to the tab "App" - there you can edit the resources and create more fields for whatever you need.
